introduce support for on_start and on_stop service hooks
compose-spec/compose-spec pull request #289
Opened 2022-12-10 18:50 UTC by ndeloof

**What this PR does / why we need it**:
Introduce support for hooks command to run after container started, and/or before container is (intentionaly) stopped

Typical use-case for this is to 
- import initial dataset in a service
- prepare service for shutdown with a dedicated command.

2022-12-10 20:13 UTC, ndeloof commented
> restart another container when a container is recreated

if you use `depends_on` ou already have such use-case supported (while, recreating containers, not just restarting)

> use “docker compose exec” to run a command within the same container that just started [ie: a minor permission change on a file after start or the use cases of the original poster]

this is exactly what `on_start` is about.


I'm reticent to giving option to run commands out of the container: while I understand this allows many advanced usages, this brings portability and security issues.

2023-01-01 10:45 UTC, EricHripko commented
I agree re: @ndeloof's point on running commands on the host - mostly on the portability front. Compose spec today is somewhat detached from the implementation and the generic "execute command on host" feature would make the spec less portable (by tying it to a specific Compose CLI and relying on specific CLI utilities existing on the host).

2023-01-01 10:52 UTC, EricHripko reviewed
Exciting - thank you for looking into this! Left a quick comment inline 💬 I'd also suggest naming the hooks something like `after_start` and `before_stop` to better indicate (through naming) when the hooks are executed, as hinted by @michaelkrieger.

2023-01-01 10:52 UTC, EricHripko commented on spec.md
> +      on_create: ./generate_server_certificate.sh
Is this meant to say `on_start` instead?

2023-01-23 10:56 UTC, laurazard approved these changes
Looks great to me ✅ ! Super happy about this change, and I think it'll simplify a ton of very common workflows. Echo @EricHripko and @ndeloof's sentiments re: execution on the host.

2023-04-02 00:39 UTC, JS-E commented
Any update on this? Awaiting a small PR tweak

2023-04-25 10:44 UTC, ulyssessouza requested changes
I think there are some steps missing:
- A global `pre` and `post`. That is analogous to a unit tests that have "BeforeEverything" and "AfterEverithing" steps.
- `pre_create` and `post_create`. Actually every `pre` and `post` for each state in the state machine of the container.
- Not running in the service container, but in another one. Or at least it shouldn't be the default.  (DEFINITELY NOT RUNNING IN THE HOST!)

2023-04-25 12:53 UTC, ndeloof commented
@ulyssessouza this proposal is based on kuke lifecycle hooks
it is only focussing on running _inside_ service container, but you can read https://github.com/compose-spec/compose-spec/issues/291 for init-containers running before `start`
About debate using entrypoint script vs post-start hook, better ask k8s users how and why they use this feature vs writing a more complex entrypoint. Same question could apply to pre-stop vs application code to react to SIGTERM to shutdown nicely

2023-04-25 12:53 UTC, closed without merging