add more info to fragements and extension
compose-spec/compose-spec pull request #356
Opened 2023-05-16 14:07 UTC by aevesdocker

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

2023-05-16 19:03 UTC, milas approved these changes

2023-05-17 09:34 UTC, ndeloof requested changes
way better than previous doc
but example merging with a sequence is invalid

2023-05-17 09:34 UTC, ndeloof commented on 10-fragments.md
> +```
this doesn't work. yaml merge `<<: *xx` can only be used with a mapping.

2023-05-19 10:15 UTC, aevesdocker commented
Thanks for catching that @ndeloof. I've updated the example with bits from your closed PR

2023-05-19 10:15 UTC, aevesdocker commented
Unsure why I'm suddenly getting build errors again and spec.md file appears deleted 🤔

2023-05-19 19:59 UTC, ndeloof approved these changes

2023-05-19 19:59 UTC, merged